apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vm
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: "0.63.6"
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
      interval: 12h
  install:
    crds: CreateReplace
    disableWait: true
    timeout: 10m
  upgrade:
    crds: CreateReplace
    disableWait: true
    timeout: 10m
  values:
    vmsingle:
      enabled: true
      spec:
        retentionPeriod: "30d"
        storage:
          storageClassName: iscsi-retain
          resources:
            requests:
              storage: 20Gi
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
          limits:
            memory: 2Gi

    vmagent:
      enabled: true
      spec:
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 512Mi

    vmalert:
      enabled: true
      spec:
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            memory: 256Mi

    grafana:
      enabled: true

    prometheus-node-exporter:
      enabled: true

    kube-state-metrics:
      enabled: true

    defaultDashboards:
      enabled: true

    defaultRules:
      create: true
      rules:
        # Disable heavy rules that cause query overload
        kubeApiserverAvailability: false
        kubeApiserverBurnrate: false
        kubeApiserverHistogram: false
        kubeApiserverSlos: false
        kubePrometheusGeneral: false
        kubePrometheusNodeRecording: false
        kubeSchedulerAlerting: false
        kubeSchedulerRecording: false
        kubeStateMetrics: false
        kubelet: false
        kubernetesApps: false
        kubernetesResources: false
        kubernetesStorage: false
        kubernetesSystem: false
        node: false
        nodeExporterAlerting: false
        nodeExporterRecording: false
        # Keep only basic VM monitoring rules
        vmHealth: true
        vmagent: true
        vmsingle: true
        alertmanager: true
