apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 30m
  chart:
    spec:
      chart: tailscale-operator
      version: "1.78.1"
      sourceRef:
        kind: HelmRepository
        name: tailscale
      interval: 12h
  install:
    crds: CreateReplace
    timeout: 10m
  upgrade:
    crds: CreateReplace
    timeout: 10m
  values:
    oauth:
      clientId: ""
      clientSecret: ""
    operatorConfig:
      hostname: "tailscale-operator"
      logging: "info"
    apiServerProxyConfig:
      mode: "true"
  valuesFrom:
    - kind: Secret
      name: tailscale-oauth
      valuesKey: Tailscale-OAuth-Client-Id
      targetPath: oauth.clientId
    - kind: Secret
      name: tailscale-oauth
      valuesKey: Tailscale-OAuth-Client-Secret
      targetPath: oauth.clientSecret
